
//! Autogenerated weights for pallet_projects
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ../../target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_projects
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/projects/src/weights.rs
// --projects
// ../../.maintain/frame-weight-projects.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_projects.
pub trait WeightInfo {
	fn add_manager() -> Weight;
	fn remove_manager() -> Weight;
	fn spend_local() -> Weight;
}

/// Weights for pallet_projects using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn add_manager() -> Weight {
		Weight::from_parts(1, 1)
	}
	fn remove_manager() -> Weight {
		Weight::from_parts(1, 1)
	}
	fn spend_local() -> Weight {
		Weight::from_parts(1, 1)
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn add_manager() -> Weight {
		Weight::from_parts(1, 1)
	}
	fn remove_manager() -> Weight {
		Weight::from_parts(1, 1)
	}
	fn spend_local() -> Weight {
		Weight::from_parts(1, 1)
	}
}
